title: 1-3-7 Model
description: A reference model for the modern digital workplace
theme: just-the-docs

url: https://marekdev.wolski.me.uk/137_model/

footer_content: "!! Please Note: as of August 2026 this site is still a WORK-IN-PROGRESS !!"
